# Generated by Django 6.0.4 on 2026-04-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_getiren_kisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gunluk_transfer_hesap_sayisi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referans_kodu',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='son_transfer_tarihi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefon',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='getiren_kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referanslar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kredi',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
