# Generated by Django 6.0.4 on 2026-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_image_customuser_profil_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biyografi'),
        ),
    ]
