# Generated by Django 6.0.4 on 2026-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='yetenekler',
            field=models.CharField(blank=True, help_text='Yetenekleri virgülle ayırarak yaz (Örn: Python, C#, Java)', max_length=500),
        ),
    ]
