# Generated by Django 6.0.4 on 2026-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_yetenekler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='yetenekler',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
