# Generated by Django 6.0.4 on 2026-05-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_alter_storeitem_css_class_alter_storeitem_kategori'),
        ('users', '0008_alter_customuser_yetenekler'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aktif_cerceve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kullananlar', to='notes.storeitem', verbose_name='Aktif Profil Çerçevesi'),
        ),
    ]
