# Generated by Django 6.0.3 on 2026-04-10 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat', models.IntegerField(default=50)),
                ('kategori', models.CharField(choices=[('Çerçeve', 'Profil Çerçevesi'), ('Tema', 'Özel Tema'), ('Rozet', 'Başarı Rozeti')], max_length=50)),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Not Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='notes/files/', verbose_name='Not Dosyası')),
                ('kapak_resmi', models.ImageField(blank=True, null=True, upload_to='notes/covers/', verbose_name='Kapak Resmi')),
                ('fiyat', models.IntegerField(default=10, verbose_name='Kredi Bedeli')),
                ('ders_kategorisi', models.CharField(choices=[('Yazılım', 'Yazılım'), ('Matematik', 'Matematik'), ('Donanım', 'Donanım'), ('Diğer', 'Diğer')], default='Yazılım', max_length=50)),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcamalar', to=settings.AUTH_USER_MODEL)),
                ('not_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note')),
                ('satıcı', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kazanclar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
