# Generated by Django 6.0.4 on 2026-04-11 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kira_baslangic', models.DateTimeField(auto_now_add=True)),
                ('kira_bitis', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
        migrations.AddField(
            model_name='note',
            name='kira_fiyatı',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='sayfa_sayisi',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='aciklama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='ders_kategorisi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='dosya',
            field=models.FileField(upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='fiyat',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='kapak_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='yukleyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='baslik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='alici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='not_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='satıcı',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='satislar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
