# Generated by Django 6.0.4 on 2026-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rental_delete_shopitem_note_kira_fiyatı_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_nadir',
            field=models.BooleanField(default=False),
        ),
    ]
