# Generated by Django 6.0.4 on 2026-04-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_is_nadir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('theme', 'Arka Plan Teması'), ('font', 'Özel Yazı Tipi'), ('frame', 'Profil Çerçevesi'), ('effect', 'Görsel Efekt (Buton vb.)')], max_length=20)),
                ('fiyat', models.PositiveIntegerField()),
                ('preview_image', models.ImageField(upload_to='store/previews/')),
                ('css_class', models.CharField(help_text='Uygulanacak CSS sınıfı adı', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='sayfa_sayisi',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='not_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.CreateModel(
            name='NotePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('yeni_dosya', models.FileField(blank=True, null=True, upload_to='packages/')),
                ('fiyat', models.PositiveIntegerField()),
                ('kapak_resmi', models.ImageField(blank=True, null=True, upload_to='package_covers/')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('notlar', models.ManyToManyField(blank=True, related_name='paketler', to='notes.note')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alinma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanter', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.storeitem')),
            ],
            options={
                'verbose_name_plural': 'Envanterler',
            },
        ),
    ]
