# Generated by Django 6.0.4 on 2026-04-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_storeitem_alter_note_sayfa_sayisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='notes/multiple/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_dosyalar', to='notes.note')),
            ],
        ),
    ]
