# Generated by Django 6.0.4 on 2026-04-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tema', 'Arka Plan Teması'), ('cerceve', 'Profil Çerçevesi'), ('yazi', 'Yazı Tipi & Efekt'), ('buton', 'Özel Buton Efekti'), ('paket', 'Not Paketi')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('css_class', models.CharField(help_text='Uygulanacak CSS sınıfı (örn: neon-glow)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanter_genel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanter_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
