# Generated by Django 6.0.4 on 2026-04-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='kira_fiyatı',
            new_name='kira_fiyati',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profil_resmi',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='satıcı',
            new_name='satici',
        ),
    ]
