# Generated by Django 6.0.4 on 2026-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_profile_peerscore_profile_yetenekler_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='peer_id',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
    ]
