# Generated by Django 6.0.4 on 2026-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_profile_peer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
