# Generated by Django 6.0.4 on 2026-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_profile_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='takip_listesi_gizli',
            field=models.BooleanField(default=False),
        ),
    ]
