# Generated by Django 6.0.4 on 2026-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_question_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
