# Generated by Django 6.0.4 on 2026-05-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_question_answer_question_answered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başarı Adı')),
                ('category', models.CharField(choices=[('academic', 'Akademik Başarı (Notlar/Dereceler)'), ('certificate', 'Sertifika (Udemy, BTK Akademi vb.)'), ('project', 'Proje & Yarışma (Teknofest, Hackathon vb.)')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurum')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kısa Açıklama')),
                ('evidence_file', models.FileField(upload_to='achievements/%Y/%m/', verbose_name='Kanıt Belgesi (SS/PDF)')),
                ('achievement_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
