# Generated by Django 6.0.4 on 2026-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, verbose_name='Biyografi'),
        ),
    ]
