# Generated by Django 6.0.4 on 2026-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_note_is_pinned_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='kategori',
            field=models.CharField(choices=[('theme', 'Arka Plan Teması'), ('font', 'Özel Yazı Tipi'), ('frame', 'Profil Çerçevesi'), ('avatar', 'Özel Profil Avatarı'), ('effect', 'Görsel Efekt')], max_length=20),
        ),
    ]
