# Generated by Django 6.0.4 on 2026-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_notification_action_text_notification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='css_class',
            field=models.CharField(blank=True, help_text='Uygulanacak CSS sınıfı adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='kategori',
            field=models.CharField(choices=[('theme', 'Arka Plan Teması'), ('font', 'Özel Yazı Tipi'), ('frame', 'Profil Çerçevesi'), ('avatar', 'Özel Profil Avatarı'), ('effect', 'Görsel Efekt (Buton vb.)')], max_length=20),
        ),
    ]
