# Generated by Django 6.0.4 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_notepackagequestion_notepackagereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='onizleme_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='note',
            name='onizleme_sayfalari',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
