# Generated by Django 6.0.4 on 2026-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_note_onizleme_dosyasi_note_onizleme_sayfalari'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepackage',
            name='is_nadir',
            field=models.BooleanField(default=False),
        ),
    ]
