# Generated by Django 6.0.4 on 2026-05-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_notepackage_is_nadir'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepackage',
            name='kira_fiyati',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.notepackage'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
