# Generated by Django 6.0.4 on 2026-05-16 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_notepackage_kira_fiyati_rental_package_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begendigi_notlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
