# Generated by Django 6.0.4 on 2026-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='shared_note',
        ),
        migrations.RemoveField(
            model_name='message',
            name='shared_package',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
